/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2017-05-04 03:23:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Charts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/menubar.jsp", Long.valueOf(1483777754170L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1483777753809L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1483777753829L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap-theme.min.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\"/>\n");
      out.write("        <link rel=\"icon\" href=\"favicon.ico\" />\n");
      out.write("        <script src=\"js/jquery-2.1.4.min.js\"></script>\n");
      out.write("        <script src=\"js/menubar.js\"></script>\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <style>\n");
      out.write("            *{\n");
      out.write("                margin: 0px auto;\n");
      out.write("                font-family: sans-serif;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            body{\n");
      out.write("                margin: auto;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"\">\n");
      out.write("    <nav class=\"navbar-fixed-top\">\n");
      out.write("        <ul>\n");
      out.write("            <li class=\"option\"><a href=\"/SupportFor-Ptiter\">Trang chủ</a>\n");
      out.write("                <h3></h3>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"option\"><a href=\"managing?action=Schedule\">Lập lịch đăng ký tín chỉ</a>\n");
      out.write("                <h3></h3>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"option\"><a href=\"managing?action=Searchmark\">Tra cứu điểm thi</a>\n");
      out.write("                <h3></h3>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"option\"><a href=\"managing?action=Charts\">Bảng xếp hạng</a>\n");
      out.write("                <h3></h3>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("        <a href=\"#\" id=\"pull\">Menu</a>\n");
      out.write("    </nav>\n");
      out.write("    ");

        String myURI = request.getServerName();
        if (!myURI.contains("localhost")) {
    
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"banner\">\n");
      out.write("        <!-- Begin W3Counter Tracking Code -->\n");
      out.write("        <script type=\"text/javascript\" src=\"https://www.w3counter.com/tracker.js\"></script>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            w3counter(98662);\n");
      out.write("        </script>\n");
      out.write("        <noscript>\n");
      out.write("        <div><a href=\"http://www.w3counter.com\"><img src=\"https://www.w3counter.com/tracker.php?id=98662\" style=\"border: 0\" alt=\"W3Counter\" /></a></div>\n");
      out.write("        </noscript>\n");
      out.write("        <!-- End W3Counter Tracking Code -->\n");
      out.write("    </div>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("        <div class=\"container text-center\" style=\"padding-top: 60px;\">\n");
      out.write("\n");
      out.write("<script src=\"js/Charts/Charts.js\"></script>\n");
      out.write("<title>Bảng xếp hạng</title>\n");
      out.write("<div id=\"show\" class=\"text-center\">\n");
      out.write("    <h3><label>Bảng xếp hạng điểm</label></h3><br>\n");
      out.write("    <table id=\"select\" cellspacing=\"0\" cellpadding=\"10\">\n");
      out.write("        <tr>\n");
      out.write("            <td>Khóa:</td>\n");
      out.write("            <td>\n");
      out.write("                <select id=\"year\">\n");
      out.write("                    <option value=\"B12\">2012</option>\n");
      out.write("                    <option value=\"B13\">2013</option>\n");
      out.write("                    <option value=\"B14\">2014</option>\n");
      out.write("                    <option value=\"B15\">2015</option>\n");
      out.write("                    <option value=\"B..\">Tất cả</option>\n");
      out.write("                </select>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td>Khoa:</td>\n");
      out.write("            <td>\n");
      out.write("                <select id=\"major\">\n");
      out.write("                    <option value=\"AT\">An Toàn</option>\n");
      out.write("                    <option value=\"CN\">Công Nghệ</option>\n");
      out.write("                    <option value=\"DT\">Điện Tử</option>\n");
      out.write("                    <option value=\"KT\">Kế Toán</option>\n");
      out.write("                    <option value=\"MR\">Marketing</option>\n");
      out.write("                    <option value=\"QT\">Quản Trị</option>\n");
      out.write("                    <option value=\"VT\">Viễn Thông</option>\n");
      out.write("                    <option value=\"PT\">Phương Tiện</option>\n");
      out.write("                </select>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td>Hệ:</td>\n");
      out.write("            <td>\n");
      out.write("                <select id=\"system\">\n");
      out.write("                    <option value=\"DC\">Đại Học</option>\n");
      out.write("                    <option value=\"CC\">Cao Đẳng</option>\n");
      out.write("                    <option value=\"LT\">Liên Thông</option>\n");
      out.write("                </select>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("<div id=\"showDiv\">\n");
      out.write("    <table id=\"charts\" cellspacing=\"0\" cellpadding=\"10\" class=\"table table-bordered table-striped table-sm mytable\">\n");
      out.write("    </table>\n");
      out.write("    <input id=\"loadmore\" type=\"button\" value=\"Tải Thêm\" class=\"button\"/>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
